# Generated by Django 3.1.2 on 2020-11-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='basket',
            fields=[
                ('bsno', models.AutoField(primary_key=True, serialize=False)),
                ('pdname', models.CharField(max_length=100)),
                ('pdqty', models.IntegerField(default=1)),
                ('pdprice', models.IntegerField()),
                ('todo_id', models.IntegerField()),
                ('done', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUploadModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ImageField(upload_to='images/%Y/%m/%d', verbose_name='가격표')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('contents', models.CharField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='memo',
            fields=[
                ('mname', models.CharField(max_length=250, verbose_name='제목')),
                ('cdate', models.DateField(default='2020-11-23', verbose_name='작성일')),
                ('mdetail', models.TextField(blank=True, max_length=1000, verbose_name='내용')),
                ('label', models.CharField(choices=[('primary', '기본'), ('success', '욕망의바구니'), ('danger', '중요'), ('warning', '기념일'), ('info', '회사')], max_length=20, verbose_name='라벨')),
                ('finished', models.BooleanField(default=False, verbose_name='계산완료')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('uemail', models.CharField(max_length=64, verbose_name='사용자명')),
                ('budget', models.IntegerField()),
            ],
            options={
                'ordering': ['-cdate'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uemail', models.CharField(max_length=64, verbose_name='사용자명')),
                ('upw', models.CharField(max_length=128, verbose_name='비밀번호')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
